### ISSUE TITLE
Improve magnifying behavior close to image borders

### ISSUE THREAD

**Issue by Mikuu** [samuelmeuli/react-magnifier#3]
Hi,

Thanks for this useful component.

I try to use this in my application, but just found the magnifying glass can't cover the image at the borders and corners.

- Case1:
in your storybook demo, you can see there is a black corner at the bottom left, as below,

<img width="640" alt="screen shot 2018-10-23 at 4 54 00 pm" src="https://user-images.githubusercontent.com/11648253/47349242-d12c5b00-d6e5-11e8-96d2-df123c6ae27e.png">

but the magnifying glass can't cover that black corner, no matter how close I move the mouse to it before the mouse move outside the original image, as below,

<img width="760" alt="screen shot 2018-10-23 at 4 53 39 pm" src="https://user-images.githubusercontent.com/11648253/47349448-3a13d300-d6e6-11e8-8642-9e07fe5454d5.png">

- Case2:
this is my storybook demo, you can see the difference at the bottom border, as below,

<img width="1226" alt="screen shot 2018-10-23 at 4 55 41 pm" src="https://user-images.githubusercontent.com/11648253/47349492-5748a180-d6e6-11e8-9391-29bca1639731.png">
 
and

<img width="1233" alt="screen shot 2018-10-23 at 4 55 24 pm" src="https://user-images.githubusercontent.com/11648253/47349513-5fa0dc80-d6e6-11e8-8df7-d070cadea83e.png">

Can you check this, thanks.

BR.
Mikuu

**Comment by samuelmeuli** [comment]
Hi @Mikuu,

Thanks for opening this issue.

What you're describing is the intended behaviour. You can't see the image corner because you're using the circle shape. If you set `mgShape="square"`, you can see what's in the corner:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/22477950/47356287-dc6e8f00-d6c3-11e8-835c-76552c22a3f8.png">

You're right that this might not be the expected behaviour of a magnifying glass though. It might be better to also display what's outside the image when hovering close to the image border, as it is done in [this library](https://github.com/lelandrichardson/react-image-magnifier):

<img width="958" alt="image" src="https://user-images.githubusercontent.com/22477950/47358066-f494dd00-d6c8-11e8-8325-046a82d0e838.png">

I'm going to have a closer look at this. It might make sense to allow switching between the two behaviours using an additional prop.

**Comment by samuelmeuli** [comment]
Hi @Mikuu,

Thanks again for your suggestions! I've now updated the component and decided to replace the old magnifying behavior and make this the new default. Furthermore, I've introduced the `mgShowOverflow` prop, which lets you choose whether you want to see the full magnifying glass when hovering close to the image borders.

I've also updated the Storybook with an example for the new prop. It would be great if you could have a quick look and tell me if the magnifier is now behaving as you're expecting it :) I will then release this as version 2.0 to NPM.

**Comment by Mikuu** [comment]
Hi @samuelmeuli,

Thanks for your nice enhancement, the functionality is much better than I expected. 👍 

I think v2.0 is very close to perfect. But I found another issue, when the source image is too high to be displayed in the viewport, I need to scroll down to the page bottom, then the magnify is not working on the image's lower area.

I tested and confirmed this defect doesn't exist in v1.1.1, so probably introduced only in v2.0. Hope you have time to also look at this.

Finally, sorry to bring you so many troubles.

BR.
Mikuu
